name: "pint action"
description: "Validate Prometheus rules using cloudflare/pint"
branding:
  color: orange
  icon: bell
inputs:
  token:
    description: "Github token to use"
    required: true
  workdir:
    description: "Working directory to use"
    required: false
    default: "."
  config:
    description: "Config file to use"
    required: false
    default: ""
  loglevel:
    description: "Log level to use"
    required: false
    default: ""
  minSeverity:
    description: "Minimum severity to report"
    required: false
    default: ""
  requireOwner:
    description: "Require all rules to have an owner set via comment"
    required: false
    default: ""
  # TODO update these
  pr_target_repo:
    description: "target repo to PR"
    required: false
    default: ""
  pr_source_repo:
    description: "source repo from PR"
    required: false
    default: ""


runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_AUTH_TOKEN: ${{ inputs.token }}
    CONFIG: ${{ inputs.config }}
    WORKDIR: ${{ inputs.workdir }}
    LOGLEVEL: ${{ inputs.loglevel }}
    MIN_SEVERITY: ${{ inputs.minSeverity }}
    REQUIRE_OWNER: ${{ inputs.requireOwner }}
    PULL_REQUEST_TARGET_REPO: ${{ inputs.pr_target_repo }}
    PULL_REQUEST_SOURCE_REPO: ${{ inputs.pr_source_repo }}
